[service]
    host    = "0.0.0.0"
    port    = 8081
    secret  = "--uuid--"                # change it !

    [service.timeouts]
        write   = "5m"
        read    = "5m"
        idle    = "10m"

[db]
    host        = "mongo"
#    host        = "localhost"
    port        = 27017
    user        = "admin"        # change it !
    password    = "admin"     # change it !
    dbname      = "doroga"
    collection  = "reqs"
    timeout     = "3s"

[storage]
#    path    = "/tmp/doroga_static"
    path    = "/var/doroga_static"
    uid     = 1000
    gid     = 1000

[form]
    allowed_formats = [
        "image/jpeg",
        "image/gif",
        "image/png",
        "image/bmp",
        "image/tiff"
    ]
    max_file_size = 5
    jpeg_quality = 96
    shrink_photo_to = 2500
    thumbnail_size = 250
    add_watermark = true
