# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "tests" ]
  pull_request:
    branches: [ "main", "tests" ]

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./backend/cmd/main

  GoSec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ynniss/golang-security-action@master
        with:
          CODE_PATH: ./backend/cmd/main
